version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./frontend:/app:ro
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:3000/dev
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app:delegated
      - backend_node_modules:/app/node_modules
    environment:
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/taskmanager?authSource=admin
      - JWT_SECRET=your_local_development_secret_key
    depends_on:
      - mongodb
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    restart: unless-stopped

  api-docs:
    build:
      context: ./backend/docs
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./backend/swagger.yml:/app/swagger.yml:ro
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  mongodb_data:
  backend_node_modules:
